### ISSUE TITLE
Selecting a sentence in translation should highlight corresponding group of nodes in armenian text and on the graph

### ISSUE THREAD

**Issue by melozzo** [performant-software/chronicleME#21]

**Comment by SteveMarvin** [comment]
Not sure what to think here, because translations can be fluid. 

On [Year 408](http://157.245.255.111/#/Edition/1089149), if the user clicks the last sentence in the translation, the last sentence in the original is highlighted. 
![Screen Shot 2020-01-21 at 11 49 46 AM](https://user-images.githubusercontent.com/18423533/72824954-27b77a80-3c44-11ea-97bf-8cfad774e44a.png)
However, if the user selects the first sentence in the translation, that same last sentence in the original is highlighted as well as stuff at the start of the original. 
![Screen Shot 2020-01-21 at 11 50 51 AM](https://user-images.githubusercontent.com/18423533/72825092-6c431600-3c44-11ea-9c09-fbe83a09ec6b.png)

**Comment by SteveMarvin** [comment]
It's hard to verify that this is correct without learning more Armenian or Google Translate stepping up more, but I am assured this is all good.
