### ISSUE TITLE
Manuscript Reading Interface

### ISSUE THREAD

**Issue by NickLaiacona** [performant-software/chronicleME#41]
For each manuscript transcription, take the TEI XML and display it using the CETEIcean (https://github.com/TEIC/CETEIcean) library. Each Manuscript Card on the Manuscripts page should have a "Read" button next to the "Download" button which leads to this interface.

**Comment by melozzo** [comment]
Its a first pass at this issue, still working on faster rendering with pre generated html

**Comment by SteveMarvin** [comment]
It's a View Transcription button rather than a Read button, but same thing. However, the manuscript itself is not appearing, despite the filename being shown above the transcription. 

A 404 is being generated on loading the Manuscripts page, and then another error is generated when the individual transcription page loads: 
![Screen Shot 2020-02-18 at 2 37 32 PM](https://user-images.githubusercontent.com/18423533/74771487-40737a00-525c-11ea-868e-9bba46fec7bd.png)
